"""
Author: Liu Chang

An example of using the data generated by generate_data.py
"""

import os.path as path
import pickle

data_path='/raid5/liuchang/quick_draw_output'

with open(path.join(data_path,'data_X'),'rb') as f:
    X=pickle.load(f)

with open(path.join(data_path,'data_Y'),'rb') as f:
    Y=pickle.load(f)

len_train_X=int(len(X)*0.8)

print(len(X))
import numpy as np
train_X=np.array(X[:len_train_X])
train_Y=np.array(Y[:len_train_X])
test_X=np.array(X[len_train_X:])
test_Y=np.array(Y[len_train_X:])